//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carritos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carritos()
        {
            this.Carrito_Detalle = new HashSet<Carrito_Detalle>();
        }
    
        public int id_carrito { get; set; }
        public int id_usuario { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime ultima_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito_Detalle> Carrito_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
