//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito_Detalle
    {
        public int id_carrito_detalle { get; set; }
        public int id_carrito { get; set; }
        public int id_inventario { get; set; }
        public int cantidad { get; set; }
    
        public virtual Carritos Carritos { get; set; }
        public virtual Inventario_Detalle Inventario_Detalle { get; set; }
    }
}
