//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones_Usuario
    {
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public string linea1 { get; set; }
        public string linea2 { get; set; }
        public string ciudad { get; set; }
        public string departamento { get; set; }
        public string pais { get; set; }
        public string codigo_postal { get; set; }
        public string telefono_contacto { get; set; }
        public bool es_principal { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
