//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitStyleDBEntities : DbContext
    {
        public FitStyleDBEntities()
            : base("name=FitStyleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrito_Detalle> Carrito_Detalle { get; set; }
        public virtual DbSet<Carritos> Carritos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Colores_Catalogo> Colores_Catalogo { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Inventario_Detalle> Inventario_Detalle { get; set; }
        public virtual DbSet<Pedido_Detalle> Pedido_Detalle { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Tallas_Catalogo> Tallas_Catalogo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
