//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario_Detalle()
        {
            this.Carrito_Detalle = new HashSet<Carrito_Detalle>();
            this.Pedido_Detalle = new HashSet<Pedido_Detalle>();
        }
    
        public int id_inventario { get; set; }
        public int id_producto { get; set; }
        public int id_talla { get; set; }
        public int id_color { get; set; }
        public int stock_actual { get; set; }
        public string sku_variante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito_Detalle> Carrito_Detalle { get; set; }
        public virtual Colores_Catalogo Colores_Catalogo { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Tallas_Catalogo Tallas_Catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Detalle> Pedido_Detalle { get; set; }
    }
}
