//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Inventario_Detalle = new HashSet<Inventario_Detalle>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_corta { get; set; }
        public string descripcion_larga { get; set; }
        public decimal precio { get; set; }
        public string url_imagen_principal { get; set; }
        public int id_categoria { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public bool destacado { get; set; }
        public string seccion { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Detalle> Inventario_Detalle { get; set; }
    }
}
