//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tallas_Catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tallas_Catalogo()
        {
            this.Inventario_Detalle = new HashSet<Inventario_Detalle>();
        }
    
        public int id_talla { get; set; }
        public string nombre_talla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Detalle> Inventario_Detalle { get; set; }
    }
}
